# Generated by Django 4.2.3 on 2023-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ann_table',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ann_table',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
