# Generated by Django 4.2.3 on 2023-08-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ann_table',
            name='image',
            field=models.ImageField(upload_to='kyc_documents/'),
        ),
    ]
