# Generated by Django 4.2.3 on 2023-08-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotes',
        ),
    ]
