# Generated by Django 4.2.3 on 2023-08-09 05:38

import base.formatchecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='aadhaar',
            field=base.formatchecker.ContentTypeRestrictedFileField(upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='driving_license',
            field=base.formatchecker.ContentTypeRestrictedFileField(upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='passport',
            field=base.formatchecker.ContentTypeRestrictedFileField(upload_to='kyc_documents/'),
        ),
    ]
