# Generated by Django 4.2.3 on 2023-08-09 06:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_kyc_aadhaar_alter_kyc_driving_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='aadhaar',
            field=models.FileField(upload_to='kyc_documents/', validators=[base.models.file_size]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='driving_license',
            field=models.FileField(upload_to='kyc_documents/', validators=[base.models.file_size]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='passport',
            field=models.FileField(upload_to='kyc_documents/', validators=[base.models.file_size]),
        ),
    ]
